### ISSUE TITLE
Core content requirements

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis_rails#126]
Review content
- [x] Models @R-Aniekwu @alainafroh @amruelama 
- [x] Front Page #71 @amruelama 
- [x] About Page #72 @amruelama 
- [x] Featured Report Page @R-Aniekwu @alainafroh @amruelama 
- [x] Custom Query #106 @R-Aniekwu @alainafroh @amruelama 
- [x] Search functionality @R-Aniekwu @alainafroh @amruelama 

Add suggestions [here](https://docs.google.com/document/d/1G3goemeZy78W9ltyWR1_oPnAagNxzuNoWv7y6O6sR30/edit)
